version: '3.1'

services:
  database:
    image: mongo:4.2.6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: banktransaction
    ports:
      - 27017:27017

  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8080:8080